# WAS 서비스 포트 설정
server:
  port: 8090


# Log4j2 기본 설정
logging:
  config: classpath:log4j2.xml

  
# Profiles 설정
spring:
  profiles:
    active: local
---
spring.profiles: local
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/pms3-multi?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    driverClassName: 